### ISSUE TITLE
String miscomparison output is not colored when using the -i switch

### ISSUE THREAD

**Issue by Dechcaudron** [funkwerk/dshould#10]
Hi,

when selecting a subset of tests to be run through `-i <regexp>` I have observed the expected-vs-actual string usually shown when strings miscompare is not colored. Is this intended behavior?

By the way, great work on the library. It is being extremely useful to me!

Regards,
Héctor

**Comment by FeepingCreature** [comment]
Yay!

Is this with unit-threaded? With the unit-threaded runner, you can force escape codes on with -e. Otherwise it'll filter them out if it isn't connected directly to a terminal, for instance if it's redirecting the output of a run for some reason.

Otherwise, I don't know what test runner adds the -i flag, so I can't say. dshould itself doesn't turn off escape codes internally, so whatever is filtering it out has to be some other lib.

**Comment by Dechcaudron** [comment]
No, just off-the-shelf dlang unittests with dshould.

-------- Original Message --------

**Comment by FeepingCreature** [comment]
Hm. Well I'm completely unable to find where "-i" is implemented, so I can't comment on how to fix that behavior. In any case, it's not something dshould has control over.

**Comment by Dechcaudron** [comment]
Wait, so the test ID lookup and execution is not managed by dshould? I would think it would just use the Phobos regexp functions to filter the unit tests to be run and then just kick them off normally.

-------- Original Message --------

**Comment by FeepingCreature** [comment]
No it's not, because we internally use it with the unit-threaded runner, which already does it for us. dshould just does `.should`.

**Comment by Dechcaudron** [comment]
I see, it makes sense not to reinvent the wheel. I will be honest, I cannot reproduce the issue I reported last night. If I come across it again, I will try to dig into it a bit more and see what comes out if. Until then we can close the issue. Apologies for the noise and thank you for the attention!

**Comment by FeepingCreature** [comment]
No problem. Honestly, I'm just happy to hear from someone using the library. :)
